##prueba: "@project.java.version@"

env: "DEV"
project: "@project.artifactId@"
api: "api-hola"


logging:
  level:
    org.springframework: ERROR
    com.mantenedor: DEBUG
  pattern:
    console: "%-5level - %logger{36}.%M - %msg%n"

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        proc:
          param_null_passing: true
    show-sql: true
  # config:
  #   import: classpath:application-message.yml
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

